/* Automatically generated by po2tbl.sed from rand.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"\
%s %s (C) 1998-2017 Erik Greenwald <erik@elfga.com>\n\
%s comes with ABSOLUTELY NO WARRANTY. Please read the GPL for details.\n\
\n\
Usage:\n\
\t<command> | %s [-lw] [-o <output file>]\n\
\t%s [-lwvh] [-f <input file>] [-o <output file>] [-s <seed>]\n\
\n", 2},
  {"\
 -l\t\tDisplay lines in random order\n\
 -w\t\tDisplay words in random order\n\
\n", 3},
  {"%s %s (C) 1998-2017 Erik Greenwald <erik@elfga.com>\n", 4},
  {"Cannot open %s for reading\n", 5},
  {"Cannot open %s for writing\n", 6},
};

int _msg_tbl_length = 6;
